author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /asodecoan1
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/emory:b55bk/pages/emory:gkj9j/single-page/
image_size:
  page:
    height: 1000
    width: 705
  small-thumbnail:
    height: 100
    width: 70
  thumbnail:
    height: 300
    width: 211
permalink: pretty
publication_info:
  author: Atlanta-Southern Dental College.
  date: '2017'
  editors:
  - Sara Palmer
  tei_xml: tei.xml
  title: Asodecoan, an annotated digital edition
show_annotation_author: true
source_info:
  author: Atlanta-Southern Dental College.
  date: 1918-1944
  pdf_url: https://readux.ecds.emory.edu/books/emory:b55bk/pdf/#page=1
  title: Asodecoan
  url: https://readux.ecds.emory.edu/books/emory:b55bk/
  via_readux: true
tagline: ', an annotated digital edition'
title: Asodecoan
url: https://sarepal.github.io
version: 0.7
